channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - matplotlib
  - numpy
  - pandas
  - r-base
  - r-forecast
  - r-data.table
  - r-tidyverse
  - r-furrr
  - scikit-learn
  - statsmodels
  - setuptools
  - pip:
      - fastcore
      - hyperopt
      - tqdm
      - pytorch-lightning
      - torch
      - jupyterlab
      - parse
